<a href="https://colab.research.google.com/github/Michaelvess22/Codemy-Pytorch-tutorial/blob/main/tensor_math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [3]:
#addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [4]:
#addition longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [19]:
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [8]:
#subtraction
tensor_b - tensor_a


tensor([4, 4, 4, 4])

In [9]:
#sub function
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [10]:
# multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [11]:
# mul longhand
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [12]:
#division
tensor_b/tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [13]:
# div longhand
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [14]:
#remiander modulus
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [15]:
#remainder longhand
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [18]:
#exponents
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [21]:
# reassignment
tensor_a += tensor_b
tensor_a
#or
tensor_a.add_(tensor_b)

tensor([16, 20, 24, 28])