<a href="https://colab.research.google.com/github/Michaelvess22/Codemy-Pytorch-tutorial/blob/main/tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

lists

In [3]:
my_list = [[1,2,3,4,5], [6,7,8,9]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9]]

numpy arrays

In [4]:
np1 = np.random.rand(3,4)
np1

array([[0.91255057, 0.97990472, 0.98007043, 0.43054124],
       [0.805176  , 0.78933584, 0.04640774, 0.87906278],
       [0.27003601, 0.92715958, 0.41976635, 0.85714925]])

In [6]:
np1.dtype

dtype('float64')

In [ ]:
tensors

In [9]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 1.3175, -0.5499,  0.9560, -0.0290],
        [ 0.2997, -0.9019, -1.2665, -0.7812],
        [-0.1238, -0.0284,  0.6067, -0.8794]])

In [10]:
tensor_3d = torch.zeros(3,4)
tensor_3d

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#create tencor out of numpy array
my_tensor